name: containerAction
description: calculator to test a Container action
inputs:
  number1:
    required: true
    default: 0
  number2:
    required: true
    default: 0
outputs:
  result:
    description: 'output of the sum of the 2 numbers'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.number1 }}
    - ${{ inputs.number2 }}
